### ISSUE TITLE
installed code has library dependency to hardcoded zoslib directory

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/libiconvport#1]
This 'works ok' if you build locally, but if you try to download the libiconv pax file from github and use it, it has the fully qualified path in the dependency 

@IgorTodorovskiIBM fyi ... we need a more 'robust' way to 'clean up' paths

**Comment by MikeFultonDev** [comment]
After thinking about this a bit, here's my proposal:

When we generate the 'pax' file in Jenkins:
- change the name of the directory structure we generate. Instead of: `<prefix>/` make it `<prefix>/<shortname>/<release>`. This is then consistent with our IBM Z and Cloud Modernization Stack naming and consistent with our /usr/lpp/IBM naming as well
- change all occurrences of `<prefix>` (e.g. `/jenkins/workspace/PortBuild`) to `ZOPEN_INSTALL_ROOT`. By changing all occurrences we will normalize all prefixes that reference other stuff that perhaps we aren't catching today, e.g. `#!<full bash path>`
- in the `setup.sh` code that we generate, we will need to determine the prefix. This is _not_ `$PWD` but instead a cleaned up version of `$PWD/../../`. With the new 'prefix' we can loop through all the files and change `ZOPEN_INSTALL_ROOT` to `${prefix}`.

This will solve this particular problem, and a whole bunch of other problems. 

@IgorTodorovskiIBM - will wait for your input before starting. This is pervasive. It will mean we need to change `zopen-build` and it will generate a new type of `setup.sh`

**Comment by IgorTodorovskiIBM** [comment]
I like it, so when we generate the pax, it needs to be generated from the top level <prefix> directory so that it can create the <shortname>/<release> dirs automatically on expansion right?

**Comment by MikeFultonDev** [comment]
Good question. Sounds right.

**Comment by MikeFultonDev** [comment]
this particular problem is fixed, but i'm leaving this open for now. @IgorTodorovskiIBM feel free to close this if the current PREFIX change we did is sufficient.

**Comment by MikeFultonDev** [comment]
all fixed now
