### ISSUE TITLE
iconv man page heading 

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/libiconvport#10]
Reporting what looks to be a surprise.

ICONV(1)                                                                   Linux Programmer's Manual

**Comment by MikeFultonDev** [comment]
Heh. Yep. Let me see why they call it 'Linux'.

**Comment by MikeFultonDev** [comment]
Asked a question on the libiconv bug channel: https://lists.gnu.org/archive/html/bug-gnu-libiconv/2023-04/msg00027.html

**Comment by gngrossi** [comment]
Any update or should I close?
thanks

**Comment by gngrossi** [comment]
Tried man iconv  
Linux Programmer's Manual

thanks

**Comment by MikeFultonDev** [comment]
I haven’t had any luck with that one yet.

**Comment by MikeFultonDev** [comment]
lets leave this open - i will come back to it after i've sorted out the other patches I am working on upstreaming if that's ok

**Comment by gngrossi** [comment]
Looks good...closing

**Comment by MikeFultonDev** [comment]
Great! Yes - they accepted the request and Bruno completed ir
