### ISSUE TITLE
man page says Linux

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/libiconvport#38]
![image](https://github.com/ZOSOpenTools/libiconvport/assets/115715798/b3c1a4af-f31f-473d-99af-abad2356ed1b)

![image](https://github.com/ZOSOpenTools/libiconvport/assets/115715798/a15218d2-9385-4974-b956-ed82539383e4)

**Comment by IgorTodorovskiIBM** [comment]
@MikeFultonDev I recall you had complained about this (or something similar). Was there any action taken on it?

**Comment by IgorTodorovskiIBM** [comment]
Ah there was:
> 2023-05-24  Bruno Haible  <bruno@clisp.org>
>        man pages: Use man page section title from groff or the distro.
        Reported by Mike Fulton <mikefultonpersonal@gmail.com> in
        <https://lists.gnu.org/archive/html/bug-gnu-libiconv/2023-04/msg00027.html>.
        * man/*.[13]: Remove section title "Linux Programmer's Manual".
       
There just has not been a new version released yet.

**Comment by gngrossi** [comment]
closing
