### ISSUE TITLE
Tag output stream from iconv __toCcsid()

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/libiconvport#6]
Should we consider using https://www.ibm.com/docs/en/zos/2.2.0?topic=lf-toccsid-convert-codeset-name-coded-character-set-id ?

_Originally posted by @IgorTodorovskiIBM in https://github.com/ZOSOpenTools/libiconvport/pull/5#discussion_r1103920684_

**Comment by gngrossi** [comment]
Installed libiconv 1.17 (Build 862)

Based on my understanding, it looks like iconv is not setting the codeset properly. I also tried not running from a bash shell but the result is the same. The file is encoded utf-8 as seen by the cat command.
also, once chtag is used to set the codeset to utf-8, git has an issue during git add
(https://github.com/ZOSOpenTools/gitport/issues/61)

bash-5.2$ iconv -f iso8859-1 -t utf-8 zopen_QQQ.special.819 > zopen_QQQ.special.UTF8

bash-5.2$ ls -lT zopen_QQQ.special.UTF8
t ISO8859-1   T=on  -rw-r--r--   1 @02858   @ISCICS1      18 Apr  4 07:39 zopen_QQQ.special.UTF8

bash-5.2$ cat zopen_QQQ.special.819
~ ^ ! | [ ] ▒ ▒
bash-5.2$ cat zopen_QQQ.special.UTF8
~ ^ ! | [ ] ¢ ¬

**Comment by MikeFultonDev** [comment]
this is now done with PR: #11

**Comment by MikeFultonDev** [comment]
Here's what I see @gngrossi - tell me if you see something different:
```
FULTONM@ZOSCAN2B bash /tmp> ls -rtlT ascii utf8
t ISO8859-1   T=on  -rw-------   1 FULTONM  SUDOGRP       13 Apr  6 21:08 ascii
t UTF-8       T=on  -rw-------   1 FULTONM  SUDOGRP       13 Apr  6 21:08 utf8

FULTONM@ZOSCAN2B bash /tmp> cat utf8
Hello world

FULTONM@ZOSCAN2B bash /tmp> cat ascii
Hello world

```

**Comment by gngrossi** [comment]
Looks like iconv is setting the "to" CCSID.

RC=(0) [SYSA] bash-5.2$ ls -lT zopen_QQQ.special.819
t ISO8859-1   T=on  -rw-r--r--   1 @02858   @ISCICS1      16 Apr  1 11:46 zopen_QQQ.special.819

RC=(0) [SYSA] bash-5.2$ cat zopen_QQQ.special.819
~ ^ ! | [ ] ▒ ▒

RC=(0) [SYSA] bash-5.2$ od -h zopen_QQQ.special.819
0000000 7e20 5e20 2120 7c20 5b20 5d20 a220 ac0a
0000020

--

RC=(0) [SYSA] bash-5.2$ iconv -f iso8859-1 -t utf-8 zopen_QQQ.special.819 > ZZZZZ.UTF8

RC=(0) [SYSA] bash-5.2$ ls -lT ZZZZZ.UTF8
t UTF-8       T=on  -rw-r--r--   1 @02858   @ISCICS1      18 Apr  6 22:34 ZZZZZ.UTF8

RC=(0) [SYSA] bash-5.2$ cat ZZZZZ.UTF8
~ ^ ! | [ ] ¢ ¬

RC=(0) [SYSA] bash-5.2$ od -h ZZZZZ.UTF8
0000000 7e20 5e20 2120 7c20 5b20 5d20 c2a2 20c2
0000020 ac0a
0000022

**Comment by MikeFultonDev** [comment]
Is everything good ? Can we close @gngrossi ?

**Comment by gngrossi** [comment]
Yes, looks good.
thanks
